### ISSUE TITLE
input becomes black-on-black when replying to a thread

### ISSUE THREAD

**Issue by rafan** [widget-/slack-black-theme#11]
When clicking on "Reply to thread" in channel, the input area becomes black-on-black and it is hard to see what I am typing. See the screenshot below (it contains text "oops... dark on dark"). 

I am using "One Dark" theme.

<img width="318" alt="screen shot 2017-06-30 at 10 14 19 pm" src="https://user-images.githubusercontent.com/2869117/27740102-5bda429e-5de3-11e7-9f04-639d4f89bf4b.png">

**Comment by widget-** [comment]
Sorry for the delay - was on vacation for awhile.

I'll see if I can get it done tonight along with the new Apps thing needing to be styled.

**Comment by Safinaaz** [comment]
Any luck with this? I really love this theme, however that black-on-black makes it a bit hard to use :)

**Comment by mtj8033** [comment]
```

	.ql-editor {
    color: #999;
	}
```

Works for me

**Comment by Safinaaz** [comment]
So the same issue occurs when replying to an uploaded file...

**Comment by ngriffin7a** [comment]
Submitted PR to fix the original issue description. Don't know if it fixes the uploaded file reply: https://github.com/widget-/slack-black-theme/pull/12

**Comment by GMartinez-Sisti** [comment]
This updated fixed the issue for me.

**Comment by widget-** [comment]
Alright thanks, I'll close this then.
