### ISSUE TITLE
Certain sections are still white

### ISSUE THREAD

**Issue by Zoooook** [widget-/slack-black-theme#16]
The "All Threads" page background and hover colors don't get skinned. Also as of today @ mentions and channel topics are not being skinned.

**Comment by ZENN0N** [comment]
For me its mainly the "company-wide-announcement" box at the top which is still white
(Running 2.8.0 64-bit on Win10)

**Comment by catskul** [comment]
I'm having the same problem. I'll try later to see if I can make a patch to fix.

**Comment by widget-** [comment]
I'd appreciate it if you could. I'm hoping my work lightens up a bit for me so that I have the mental energy to actually go and fix all the issues at some point but it's probably at least a week away.

**Comment by catskul** [comment]
I've never tried for this project  and am super busy so the likelihood of this happening is like 20%.

If anyone else wants to try, plan was to assume the CSS was the same as thel web app. Muck with it in chrome using the inspector, and then try it out in the "native app" to prove that was right.

**Comment by widget-** [comment]
They should be mostly the same, though the native app might not have as many containers since each team is loaded up in the Electron equivalent to being in an iframe.

You can also inspect the native app directly. See issue #14

**Comment by widget-** [comment]
Closing in favor of #19
