### ISSUE TITLE
Is it possible to use this theme from the web?

### ISSUE THREAD

**Issue by humitos** [widget-/slack-black-theme#17]
Just that, thank you!

**Comment by Rosseyn** [comment]
Recommend using a css override extension for whatever browser you roll. Add colors to the corresponding classes and ride off into the sunset like a boss.

**Comment by widget-** [comment]
You should be able to copy/paste it into Stylish but I haven't tried it myself.

**Comment by widget-** [comment]
Apparently userstyles.org doesn't allow `@import` statements in their hosted styles and I'm not particularly willing to keep it updated all the time yet, but you can create a Stylish theme yourself with the following:

```css
@import url("https://cdn.rawgit.com/widget-/slack-black-theme/master/custom.css");
```

and apply it to `URLs on the domain: slack.com`.

Alternatively, [Dark Reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=en) looks great with Slack on the web.
