### ISSUE TITLE
Some CSS not applied

### ISSUE THREAD

**Issue by Cousken** [widget-/slack-black-theme#18]
Hello!

On Windows using the 1.8.0 64-bit Desktop Client, the result of One Dark are as follows:

![capture](https://user-images.githubusercontent.com/232056/30798035-554edbf4-a1d8-11e7-916d-b68b6151c12e.PNG)

To me it looks like some CSS styles don't get applied, perhaps the tag was changed? 

What i did exactly:

- Edited my index.js as per Installation instructions on the git page.
- Copy-pasted the CSS for One Dark to replace rows 67-79
- Restarded Slack.

**Comment by caiceA** [comment]
i have the same issue

**Comment by caiceA** [comment]
@Cousken did you try fixing this ?

**Comment by caiceA** [comment]
![screen shot 2017-09-30 at 15 33 42](https://user-images.githubusercontent.com/16766231/31046192-ca9b4346-a5f4-11e7-9ece-936095ae051d.png)

**Comment by caiceA** [comment]
i fixed it myself

**Comment by Cousken** [comment]
Cool, i don't have the skill/time to look into it, just wanted to notify about the error. Did you make a pull request?

**Comment by caiceA** [comment]
![screen shot 2017-09-30 at 23 21 43](https://user-images.githubusercontent.com/16766231/31049575-310a31be-a636-11e7-810a-0462728c2e86.png)
![screen shot 2017-09-30 at 23 21 56](https://user-images.githubusercontent.com/16766231/31049576-310b85c8-a636-11e7-9839-ed987338c73a.png)

**Comment by caiceA** [comment]
i made changes to the css myself and i am now loving it, i have customize it slightly and works super well for me. i can help you if you want me to do

**Comment by mate2002** [comment]
Do a pull request if you can

**Comment by ViktorQvarfordt** [comment]
I've fixed some stuff that annoyed me. You can have a look in my fork https://github.com/ViktorQvarfordt/slack-black-theme

**Comment by widget-** [comment]
K I think I've got most of the theme fixed, so for now I'm going to close issues that aren't tracking a specific broken part (e.g. the thread page) 👍
