### ISSUE TITLE
Styling Isses 

### ISSUE THREAD

**Issue by caiceA** [widget-/slack-black-theme#19]
![screen shot 2017-09-30 at 02 25 12](https://user-images.githubusercontent.com/16766231/31040348-aeaa8f34-a586-11e7-855a-d2e89028fc72.png)

**Comment by caiceA** [comment]
![screen shot 2017-09-30 at 02 25 32](https://user-images.githubusercontent.com/16766231/31040351-b8978a24-a586-11e7-9549-a7bd6b7c65bb.png)

**Comment by jsapaugh** [comment]
When opening a thread to a message the `<label` class="checkbox">' the font color is still dark.
![label-checkbox](https://user-images.githubusercontent.com/16311466/31577330-211a6016-b0d2-11e7-980b-edddcb89cb18.PNG)

**Comment by widget-** [comment]
Threads are still broken but I got the sidebar fixed now 😅

**Comment by Zoooook** [comment]
Well, now my Slack sidebar theme stopped working :(

**Comment by widget-** [comment]
@Zoooook Ah yeah, this theme was supposed to be overwriting the sidebar themes from the beginning but it was broken for the last month or so.

Ideally as part of #3 I'll be able to separate those out better so it'll be easier to remove.

**Comment by Zoooook** [comment]
Are there any workarounds? At https://cdn.rawgit.com/widget-/slack-black-theme/master/custom.css I see:

   /* These should be less important: */
   --background-hover: rgba(255, 255, 255, 0.1);
   --background-light: #AAA;
   --background-bright: #FFF;

   --border-dim: #666;
   --border-bright: var(--primary);

   --text-bright: #FFF;
   --text-special: var(--primary);

   --scrollbar-background: #000;
   --scrollbar-border: var(--primary);

Is there any sort of mapping between these and:

column_bg
menu_bg
active_item
active_item_text
hover_item
text_color
active_presence
badge

**Comment by caiceA** [comment]
i fixed / customized css myself 

Please use this CSS Path 
http://foxshift.com/c.css  

and I liked this second colors:  

--primary: #61AFEF;
--text: #ABB2BF;
--background: #282C34;
--background-elevated: #3B4048;

everything should be fine. i am using for myself. 

<img width="1014" alt="screen shot 2017-10-23 at 21 09 02" src="https://user-images.githubusercontent.com/16766231/31908113-25a8bedc-b836-11e7-9755-9d350f2c4c12.png">

**Comment by Zoooook** [comment]
text color in sidebar still broke with that workaround ^

I may just grab an old version of the code and hardcode it in the file instead of fetching from URL

**Comment by caiceA** [comment]
i don't remember that but i think i used to fixed that from Slack actual preference or settings you can do / customize any color 
but i did fixed the thread problem and i am ok with my css so far

**Comment by widget-** [comment]
@Zoooook The sidebar mostly inherits from the `background-elevated` and `text` colors. If you'd like to modify the code it's easy to fork it (top-right corner) and edit a local branch.

@caiceA If you've fixed threading could you please push to a fork and submit a pull request?

**Comment by caiceA** [comment]
@widget-  
@Zoooook 

i just fixed many issues please use this css.  i just updated 5 mins ago with many other fixings 

http://foxshift.com/c.css  

I don't know how to do push and pull request i dont use github. but please use my CSS and you will find it much better than the original one

**Comment by Zoooook** [comment]
@widget- 

Forked. Just rolled back your latest commits and threw my own colors in it. Sidebar is back

**Comment by widget-** [comment]
Closing as I believe I've fixed all of @caiceA's issues. There's still one in #20 but I'll track that in that issue.

**Comment by Zoooook** [comment]
Is there an issue somewhere to track having a full sidebar theme on par with Slack's?

**Comment by widget-** [comment]
@Zoooook it's working fine for me

![ec597e](https://user-images.githubusercontent.com/7691630/32201014-862f345e-bda2-11e7-9406-7077cd8badde.png)

**Comment by Zoooook** [comment]
You're able to customize the sidebar with the level of granularity that Slack's customizer offers? Do you mind telling me where you put the 8 colors in?

**Comment by widget-** [comment]
@Zoooook No, but it gets themed correctly, which the second post was in reference to.

If you don't want your Slack to be themed then I suggest not using a theme.

**Comment by Zoooook** [comment]
I think the use case is pretty clear. I'd like a dark background on my main Slack window instead of the uncustomizable blinding white that it comes with, but I don't want to lose the control I already have over my sidebar. Should I make a feature request for this?

**Comment by skewuo** [comment]
It's broken.
