### ISSUE TITLE
Hover and Font Now Broken

### ISSUE THREAD

**Issue by blackdrago** [widget-/slack-black-theme#42]
After fixing the dark mode with the fix described in https://github.com/widget-/slack-black-theme/issues/34#issuecomment-350708922 - I am experiencing a new issue. The text is way too dark (even when I set it to #cccccc), and when I hover over things, the background goes from dark to white (over that specific message). 

Is there a way to control the hover settings or to fix the font color?

**Comment by mliq** [comment]
This is happening to me also, but strangely, only on one of my 7 slack workspaces. Not sure how that could be...

**Comment by blackdrago** [comment]
Yes, I just found and tried https://github.com/widget-/slack-black-theme/issues/39#issuecomment-356698404 and so far it has been working. I've updated my own repo with the information.  Thanks!
