### ISSUE TITLE
Slack 3.2.0 broken again

### ISSUE THREAD

**Issue by neotron** [widget-/slack-black-theme#52]
Sadly, 3.2.0 (Mac) is now back to white background etc.

**Comment by jamesbascle** [comment]
Same on windows.  Everything is the same except the actual text background and text (white and black)

**Comment by Ghostpants77** [comment]
yup same here. imagine my horror when i went to log in to work and saw that i would be staring at a white screen all night... I just removed the 3.2.1 folder from the slack folder and presto back to my beautiful 
black screen

**Comment by steveharman** [comment]
Hi @Ghostpants77 - would you be able to expand on your method please? I'm struggling to find a "3.2.1 folder" inside the Slack bundle (Mac) and am desperate to get "back to black".   

Thanks,

Steve

**Comment by richardcane** [comment]
I'm on 3.2.0 and all the fixes listed in #48 still work.

**Comment by steveharman** [comment]
+1 

I just re-applied the code @richardcane linked to (in 3.2.0 Mac) and I'm "back to black".  Having had yet another discussion with SlackHQ on Twitter about this.  I know, I know, fruitless as ever.  

Maybe Apple's upcoming dark theme feature in the next macOS will help (Mac users...)

**Comment by willpower232** [comment]
When slack updates to a new version, it creates a new folder with all the new code in so if you want to keep using the customisations, you'll have to modify the interop file in the new folder.

Your previously modified interop file is probably still in the old version folder so you can copy the exact modifications you want.

**Comment by jamesbascle** [comment]
This is the first time I ever try to install it and when I pasted the stuff
in the js file and loaded it, everything turned black except the main text
area where the things you and others say goes

**Comment by neotron** [comment]
It seems I did something wrong, and I can indeed get it work again. Disregard.

**Comment by designbyadrian** [comment]
> Maybe Apple's upcoming dark theme feature in the next macOS will help (Mac users...)

No, apps have to support Dark Mode, it's not an automatic fix. macOS can't assume which areas should be inverted.
