### ISSUE TITLE
add theming for default text in message window.

### ISSUE THREAD

**Issue by rphaedrus** [widget-/slack-black-theme#6]
Before someone starts typing in a new window, it says something like "Message #general".  That text is currently not rethemed and nearly disappears on a dark theme.  Once the user starts typing, it uses the color for regular messages and appears fine.

<img width="682" alt="screenshot 2017-04-24 11 12 02" src="https://cloud.githubusercontent.com/assets/1530617/25346929/dd7ad032-28de-11e7-8fe8-d4eca62bb13a.png">

**Comment by rphaedrus** [comment]
The example is using the "Low Contrast" variant.

**Comment by widget-** [comment]
Huh, I thought I made a bug out of this already, but I guess not. Thanks for reminding me 👍

**Comment by widget-** [comment]
Fixed in 163ebcd8
