### ISSUE TITLE
Chat box background is still staying in white v3.2.0

### ISSUE THREAD

**Issue by khanhletv** [widget-/slack-black-theme#62]
Hi there,

I have applied some sample color schema but the chat box background still stay in white.

Thanks and regards,

**Comment by jhollowed** [comment]
Currently experiencing the same issue :( Slack version 3.2.1 on Ubuntu 16.04

**Comment by MalPr0c3ss** [comment]
Same here...

Win 10 Pro x64 
ver. 10.0.17134

**Comment by Blizzardo1** [comment]
I'm also experiencing this.

**Comment by codycodes** [comment]
me too!

**Comment by intere** [comment]
@Nockiro has fixed this in this PR: https://github.com/widget-/slack-black-theme/pull/60

**Comment by khanhletv** [comment]
Thank you, I will try and let you know once it was fixed.

**Comment by khanhletv** [comment]
And it is still white

**Comment by intere** [comment]
@khanhletv - it is fixed, you have to (temporarily) reference `https://raw.githubusercontent.com/Nockiro/slack-black-theme/3ea2efdfb96ccc91549837ab237d57104181bbf8/custom.css` instead of the css that's currently in master.  Once that PR gets merged into master, it will be fixed.

**Comment by khanhletv** [comment]
@intere yep, it works perfectly. Thanks for helping me out and this issue should be closed for now.

**Comment by jhollowed** [comment]
referencing the alternative css url given above by @intere had no change for me on Ubuntu 16.04

**Comment by zerodivisionerr** [comment]
> @khanhletv - it is fixed, you have to (temporarily) reference `https://raw.githubusercontent.com/Nockiro/slack-black-theme/3ea2efdfb96ccc91549837ab237d57104181bbf8/custom.css` instead of the css that's currently in master. Once that PR gets merged into master, it will be fixed.

Thank you so much! Verified working on MacOS Mojave, Slack version 3.3.3!

**Comment by mingrammer** [comment]
It works for me too

**Comment by josephtoles** [comment]
This fix works on Linux running Slack version 3.3.3.

**Comment by monkpit** [comment]
This fix makes all colors from the Jenkins bot turn to black. They used to be various colors based upon the status of the Jenkins job (Green for success, red for failed, etc)...
![screen shot 2019-01-02 at 11 03 15 am](https://user-images.githubusercontent.com/5297293/50602882-42bf1d00-0e7e-11e9-8268-a7dbe5d1fdf6.png)

**Comment by Nockiro** [comment]
Hi @monkpit,
I didn't continue with the pull request here as slack 3.3 needed other fixes and I didn't want to open a new pull request with the old one not merged yet.
Despite that, I continued to adjust the theme on my fork - including the mentioned colors, if you try `https://raw.githubusercontent.com/Nockiro/slack-black-theme/master/custom.css`, the colors should work correctly.

**Comment by harveymonster** [comment]
Hi @Nockiro, I linked to the CSS on your fork and noticed that if you edit a message from within a thread, the textbox doesn't have the dark background. 

![image](https://user-images.githubusercontent.com/1637182/50646867-381b8b00-0f45-11e9-9cc5-b2644985461a.png)

**Comment by Nockiro** [comment]
Hi @harveymonster,
thanks for the hint! Fixed it and gave it the same background the standard edit inputs have, the elevated background.

**Comment by mark-bixler** [comment]
**Confirmed this works on Mojave, Slack 3.3.6.** 

If you're having issues on Mojave, verify the way you're editing your `index.js` & `ssb-interop.js` files. 

I originally was using **_vscode_** to edit, copy and paste and didn't realize formatting was all jacked up.

I ended up using **_textmate_** to copy and paste css and it works great now!

**Comment by rsionnach** [comment]
There is still a white box appearing at the top in All Unreads and All Threads.

![slack_theme](https://user-images.githubusercontent.com/3519111/51678663-da72df80-1fd4-11e9-8879-2941b6eaf1de.png)

**Comment by CliffWheadon** [comment]
@kyub That appears to be gone if you switch to using the most recent css from Nockiro's fork: ```https://raw.githubusercontent.com/Nockiro/slack-black-theme/master/custom.css```

**Comment by bjorkmeister** [comment]
> @khanhletv - it is fixed, you have to (temporarily) reference `https://raw.githubusercontent.com/Nockiro/slack-black-theme/3ea2efdfb96ccc91549837ab237d57104181bbf8/custom.css` instead of the css that's currently in master. Once that PR gets merged into master, it will be fixed.

This works on MacOS Mojave 10.14.2. Thanks.

**Comment by harveymonster** [comment]
Hey @Nockiro, I'm assuming slack has made a layout change around threads recently because the reply box in a thread is no longer dark.
![image](https://user-images.githubusercontent.com/1637182/51988679-4d67d480-2473-11e9-9f6e-dc288b8f5950.png)

Also, I noticed that if you are a part of a slack team where the admin has limited who can post to the "general" channel the message that replaces the textbox to type a message is still light.
![image](https://user-images.githubusercontent.com/1637182/51988703-58226980-2473-11e9-8fce-4352f65b9b22.png)

**Comment by Nockiro** [comment]
Hi @harveymonster,
thanks for noticing! Fixed both (and with it a few other things in the process).

**Comment by dchaid** [comment]
Feeling dumb. I'm using https://raw.githubusercontent.com/Nockiro/slack-black-theme/master/custom.css but my theme is still very, very white. 


[ssb-interop-dchaid.txt](https://github.com/widget-/slack-black-theme/files/2818324/ssb-interop-dchaid.txt)

**Comment by Nockiro** [comment]
In the file you attached it seems like you added the code somehow nested and twice? That impacts the result, you have to use the code specified in the [Readme](https://github.com/Nockiro/slack-black-theme/blob/master/readme.md) from line 100 in your case.

**Comment by edswangren** [comment]
Not working at all for me, Win10 slack 3.3.6 

The master version has the white message area and it seems like neither of the new css links in this thread are being loaded.

[index.txt](https://github.com/widget-/slack-black-theme/files/2833284/index.txt)
[ssb-interop.txt](https://github.com/widget-/slack-black-theme/files/2833285/ssb-interop.txt)

**Comment by jhollowed** [comment]
I've tried many times over the past few months, and none of the solutions here work for me either on Ubuntu 16.04, Slack 3.3.3. Why can't this finally be fixed in master? It literally makes the dark theme not dark

**Comment by iniquityx2** [comment]
Confirmed this works on Slack 3.3.7 64 windows 10

**Comment by edswangren** [comment]
Working for me after moving to 3.3.7 as well. No idea.

**Comment by mcbaer** [comment]
Not able to get this to work on Slack 3.3.8
- List of "Chats" far left is black; but channel list and chat are not effected by styling.

**Comment by iniquityx2** [comment]
Worked for me just fine on 3.3.8 - Windows 10 x64

**Comment by bison92** [comment]
@iniquityx2  please tell us what you had to do ??

**Comment by iniquityx2** [comment]
nothing other than going into the new folder location \slack\app-3.3.8\resources\app.asar.unpacked\src\static\index.js and and ssb-interop.js and inserting the section from the main help on this repo.

I did of course have to put in the modified css https://raw.githubusercontent.com/Nockiro/slack-black-theme/3ea2efdfb96ccc91549837ab237d57104181bbf8/custom.css

This has worked on two different windows 10 x64 machines without issue

**Comment by Snowflake6** [comment]
Odd.  This worked fine for me on 3.3.7, but on 3.3.8 i'm back to getting a white message area with black text.  Both with the stock section from the readme.md and with the modified css that @iniquityx2 mentions.  Same result.

**Comment by Snowflake6** [comment]
Gah.  And now, after four re-starts, it starts working.  No change to the code.  I guess there's some cache-ing going on somewhere?

**Comment by iniquityx2** [comment]
Glad it started working for you all.  Was starting to wonder if I should post my configs.

I didn't experience the delay on getting it to work though there was about 5 seconds where it was the normal theme and then it switched over

**Comment by Snowflake6** [comment]
And now Windows is offering an update, so maybe it was running slow for some reason as well while the update was downloading.  In any case, seems to be working after a short delay.

**Comment by iniquityx2** [comment]
Still working on Slack 3.40
