### ISSUE TITLE
Slack Linux app 3.3.3 white background

### ISSUE THREAD

**Issue by emersonsiega** [widget-/slack-black-theme#73]
The background still white and some menus are breaking.

![image](https://user-images.githubusercontent.com/2227499/48587261-a23a8b00-e919-11e8-9864-2761cae0f444.png)

**Comment by duynguyenhoang** [comment]
Can you try https://github.com/widget-/slack-black-theme/issues/62#issuecomment-410256441 ?

**Comment by gilad-solter** [comment]
> Can you try [#62 (comment)](https://github.com/widget-/slack-black-theme/issues/62#issuecomment-410256441) ?

I had the same issue and replacing the css url worked for me

**Comment by emersonsiega** [comment]
> Can you try [#62 (comment)](https://github.com/widget-/slack-black-theme/issues/62#issuecomment-410256441) ?

Yes, it works
