### ISSUE TITLE
3.3.4 content area is white

### ISSUE THREAD

**Issue by tobsn** [widget-/slack-black-theme#76]
how do i debug that? how can i get the inspector into that window? (osx)

**Comment by ConorPM** [comment]
https://github.com/widget-/slack-black-theme/issues/62#issuecomment-410256441 did the job for me :)

**Comment by juliano-felipe** [comment]
Also, check this out: https://github.com/widget-/slack-black-theme/issues/76

**Comment by tobsn** [comment]
@ConorPM works - since its a PR I'm closing this.

For everyone else: It's in a PR, fix is going to get merged, if you can't wait, like me, use above linked issue 62 and that guys PR css link.
