### ISSUE TITLE
Multiple teams

### ISSUE THREAD

**Issue by dharmaturtle** [widget-/slack-black-theme#9]
Is there a way to make this work for multiple teams? This themes my first team, but the rest retain the original CSS

Thanks!

**Comment by MRGiacalone** [comment]
Also looking to enable this. Have you had any luck?

**Comment by widget-** [comment]
It works sometimes if you go through and load all the teams right as it's still starting up.

Tried messing with mutation event triggers, still haven't found anything to make sure it works if you don't check the teams 'til a few minutes in consistently.
